name: Variables and Secrets

on: workflow_dispatch

env:
  MY_NAME: "Kamal"
  MY_PASSWORD: ${{secrets.MY_PASSWORD}}
  MY_API_KEY: ${{secrets.MY_API_KEY}}

jobs:
  printVariables:
    runs-on: ubuntu-latest
    steps:
      - name: print
        run: echo "${{env.MY_NAME}}"

  printVariablesInOtherEnv:
    runs-on: ubuntu-latest
    environment: testing  # this job will use testing environment created on github
    steps:
      - name: print
        run: echo "Here the password is not the same as the printVariables job while both having the same name"
